project_id = "yojzaghwrznytnkksujw"

[functions.fetch-cnpj]
verify_jwt = false

[functions.fetch-nfe]
verify_jwt = false

[functions.fetch-cte]
verify_jwt = false

[functions.extract-pdf-value]
verify_jwt = false

[functions.extract-cte-pdf]
verify_jwt = false
